#!/usr/bin/env bash
#Will display Best School 10 times, but for the 9th iteration, displays
#Best School and then will write Hi on a new line
a=1
while [ $a -le 10 ]
do
	echo "Best School"
	if [ $a -eq 9 ]; then
	   echo "Hi"
	fi
	a=$((a+1))
done