#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10
a=1
while [ $a -le 10 ]
do
	if [ $a -eq 4 ]; then
	   echo "bad luck"
	elif [ $a -eq 8 ]; then
	   echo "good luck"
	else
	   echo "Best School"
	fi
	a=$((a+1))
done