#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 20
b=1
while [ $b -le 20 ]
do
	echo $b
	case $b in
	     4) echo "bad luck from China"
	     	;;
	     9) echo "bad luck from Japan"
	        ;;
	     17) echo "bad luck from Italy"
	        ;;
        esac
	b=$((b+1))
done