#!/usr/bin/env bash
# Connect to the server using ssh with the private key ~/.ssh/school and the user ubuntu

#!/bin/bash

passphrase="betty"

ssh-keygen -t rsa -b 4096 -f ~/.ssh/school_temp

echo "$passphrase" | ssh-keygen -p -P "" -N "" -f ~/.ssh/school_temp

mv ~/.ssh/school_temp ~/.ssh/school

echo "RSA key pair created successfully."
